### PR TITLE
Added support for nested translation files

### PR DESCRIPTION
**Pull request by markwalet**
Added a where clausule to the registered routes to accept slashes.

Note sure if the extra added getView method is needed anymore. Can someone confirm?

### CODE REVIEW

**Comment by barryvdh** [comment]
can't we just urlencode the group?
Doesn't this lead to problems with routes, eg. the `/delete/{group}/{key}` route, when group matches everything?

**Comment by markwalet** [comment]
You only can only replace the "/" with something that can't be in an array key. So no, I don't think so.
Maybe you should use id's to get the correct page? Instead of filenames.

**Comment by carlosrgzm** [comment]
@markwalet You have an error in line 91 (a ; not in place) 
`($router->post('/delete/{group}/{key}', 'Controller@postDelete');->where('group', '.*')`

I've testing loading, saving, importing and exporting all keys with subfolders and apparently is working fine (after fixing the problem in line 91).

**Comment by markwalet** [comment]
Is this going to be merged?

**Comment by barryvdh** [comment]
Is this tested? What about the comment of the ;?

**Comment by markwalet** [comment]
Oh sorry. I thought I saw a commit that fixed this issue. I will fix this today

**Comment by carlosrgzm** [comment]
I made this change and with the commit (https://github.com/carlosrgzm/laravel-translation-manager/pull/1/files) the ; problem is fixed. If I'm not wrong this pull request is already merge, isn't it?

**Comment by barryvdh** [comment]
@carlosrgzm You merged it in your own fork.

Here there is still missing a `;`

**Comment by carlosrgzm** [comment]
Ok, I going to try to apply to your repository and then I'll delete my fork.

**Comment by markwalet** [comment]
Fixed the bug in my own branch now.

**Comment by barryvdh** [comment]
That is reverted in #295
It needs a seperate regex, because it's not compatible with the json translations otherwise.

**Pull request merged**
