### PR TITLE
L5.1. compatibility

### PR DESCRIPTION
**Pull request by Riesjart**
lists() method has changed in L5.1, causing array_merge errors in your controller

### CODE REVIEW

**Comment by barryvdh** [comment]
Ehh, this will cause errors on L5.0, so can you also remove 5.0.x from composer.json?

**Comment by Riesjart** [comment]
Good idea, done. Could be a good idea to remove 5.1.x from you composer.json too.

**Comment by mvdstam** [comment]
@barryvdh Can this be merged + tagged? :smile:

**Comment by barryvdh** [comment]
Sorry, didn't see @Riesjart changed the composer.json already. Merged and tagged `v0.2.0`!

**Comment by mvdstam** [comment]
Thanks! :smile:

**Comment by barryvdh** [comment]
Does https://github.com/barryvdh/laravel-translation-manager/commit/19207f1fc1548372ec434ff78f55e063afcebf1b still work for you guys?

**Pull request merged**
