### PR TITLE
Reintroduce search

### PR DESCRIPTION
**Pull request by RogueSheep-nl**
Re-activates the search modal for the L5 version.

### CODE REVIEW

**Comment by barryvdh** [comment]
Cool thanks, did you verify all is working? Can I merge this?

**Comment by RogueSheep-nl** [comment]
Yep, I did test it, worked fine for me.

**Comment by barryvdh** [comment]
Thanks!

**Comment by RogueSheep-nl** [comment]
Thanks Barry for the quick response and integration!

**Pull request merged**
