### PR TITLE
Change view parameter to prevent 404 not found error

### PR DESCRIPTION
**Pull request by sangnguyenplus**
Hi @barryvdh,
I getting this error with current URL of your repository.

Error

So I changed URL and it's working for me.

Result

Please review and help me merge this pull request.

Thanks.

### CODE REVIEW

**Comment by carlosrgzm** [comment]
I'm having the same issue. Your changes fixed my problem. I hope this pull request is going to be merged. Thanks.

**Comment by carlosrgzm** [comment]
Hi again. I think the merge is not working properly (sorry for the previous comment). 

After the merge is working fine for loading the keys, but when you go to edit and save it's failing. The main problem is with translations which are inside folders. It works fine with if the keys are in /en/auth.php but is not working if it exists subfolders like  /en/admin/auth.php.

So I think it needs some more changes to work properly. I'll try it and do a pull request if I got something working.

**Comment by barryvdh** [comment]
Reverted

**Comment by carlosrgzm** [comment]
The poblem can be fixed applying changes of this pull request https://github.com/barryvdh/laravel-translation-manager/pull/142

**Pull request merged**
