### PR TITLE
Web interface update #48 continue

### PR DESCRIPTION
**Pull request by gazben**
The request contains all the work made in #48, and fixes the merge conflicts plus fixes the missing groups error during import.

### CODE REVIEW

**Comment by gazben** [comment]
The main work is done by: @letrunghieu

**Comment by JapSeyz** [comment]
This breaks the $this->jsonSet() method in Manager.php on Line 311.

Meaning that it completely breaks any __json files trying to be saved.

**Comment by gazben** [comment]
@JapSeyz The jsonSet method has been readded in #234

**Comment by JapSeyz** [comment]
@gazben Alright, no worries. I'll close mine

**Pull request merged**
